/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HamperLead = IDL.Record({
  'name' : IDL.Text,
  'occasionType' : IDL.Text,
  'email' : IDL.Text,
  'preferredItems' : IDL.Text,
  'deliveryLocation' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
  'budgetRange' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(HamperLead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHamperLead' : IDL.Func([HamperLead], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HamperLead = IDL.Record({
    'name' : IDL.Text,
    'occasionType' : IDL.Text,
    'email' : IDL.Text,
    'preferredItems' : IDL.Text,
    'deliveryLocation' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
    'budgetRange' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(HamperLead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHamperLead' : IDL.Func([HamperLead], [], []),
  });
};

export const init = ({ IDL }) => { return []; };